// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuOFObNHuOiHPGAAI3zImAE7ftSrU_GTM',
    appId: '1:150406492600:web:68f93b60b917f97eefdf4d',
    messagingSenderId: '150406492600',
    projectId: 'todocollab-4282f',
    authDomain: 'todocollab-4282f.firebaseapp.com',
    storageBucket: 'todocollab-4282f.firebasestorage.app',
    measurementId: 'G-85GHYTFLTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjUAH7n2EtpyButuznKHc5UXUKIyU2fE',
    appId: '1:150406492600:android:cc6b337fc49c1bffefdf4d',
    messagingSenderId: '150406492600',
    projectId: 'todocollab-4282f',
    storageBucket: 'todocollab-4282f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1x967sedjLdtROoau3Vx-PVnhjIVIAbQ',
    appId: '1:150406492600:ios:311a108b7f67702aefdf4d',
    messagingSenderId: '150406492600',
    projectId: 'todocollab-4282f',
    storageBucket: 'todocollab-4282f.firebasestorage.app',
    iosBundleId: 'com.example.yourTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1x967sedjLdtROoau3Vx-PVnhjIVIAbQ',
    appId: '1:150406492600:ios:311a108b7f67702aefdf4d',
    messagingSenderId: '150406492600',
    projectId: 'todocollab-4282f',
    storageBucket: 'todocollab-4282f.firebasestorage.app',
    iosBundleId: 'com.example.yourTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuOFObNHuOiHPGAAI3zImAE7ftSrU_GTM',
    appId: '1:150406492600:web:5fd6c98121cb6784efdf4d',
    messagingSenderId: '150406492600',
    projectId: 'todocollab-4282f',
    authDomain: 'todocollab-4282f.firebaseapp.com',
    storageBucket: 'todocollab-4282f.firebasestorage.app',
    measurementId: 'G-50D10LYX49',
  );
}
