import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:your_task_app/data/local_database.dart';
import 'package:your_task_app/firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:your_task_app/viewmodels/auth_viewmodel.dart';
import 'package:your_task_app/viewmodels/task_viewmodel.dart';
import 'package:your_task_app/views/auth_screen.dart';
import 'package:your_task_app/views/task_list_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  final AppDatabase localDb = AppDatabase(); // Initialize Drift DB

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthViewModel()),
        ChangeNotifierProvider(create: (_) => TaskViewModel(localDb)),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Collaborative Task App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Consumer<AuthViewModel>(
        builder: (context, authViewModel, _) {
          if (authViewModel.isAuthenticated) {
            return const TaskListScreen();
          } else {
            return const AuthScreen();
          }
        },
      ),
    );
  }
}